### ISSUE TITLE
Migrate dispatcher to standartjs

### ISSUE THREAD

**Issue by chaos-adept** [spaceshipyard/mars-rover-dispatcher#17]
for reference - https://standardjs.com/

**Comment by vicnbt** [comment]
left my robot at work, need to check if it works and merge to the master

**Comment by chaos-adept** [comment]
@vicnbt  Could you push your changes in the "feature" branch?

**Comment by chaos-adept** [comment]
so far it looks that the standardjs is not presented in the client package.json
