### ISSUE TITLE
Improve control panel

### ISSUE THREAD

**Issue by vicnbt** [spaceshipyard/mars-rover-dispatcher#2]
- [x] New graphical joystick
- [ ] Each button should be mapped to keyboard
- [ ] Remove scroll for web-page
- [ ] Messages autoscroll in the textarea
- [x] Should send command for moving onPress and release onRelease

**Comment by chaos-adept** [comment]
https://github.com/qbolec/Joydiv could be used, we could use one instance for moving and one for camera

**Comment by chaos-adept** [comment]
point `New graphical joystick` is resolve in a2dad1a290f2d18e27c242f15047561cc63b2074 , i think it makes sense to resolve this ticket, because joystick cover all causes, messages in the screen might be reworked in the spearated work wich will be related to UX improvements

**Comment by chaos-adept** [comment]
i think it makes sense to consider it as resolved for now, i have tried to test https://github.com/spaceshipyard/mars-rover-node-bridge/issues/1 with physical servos, it works fine
