### ISSUE TITLE
Web Interface should be comfortable and clear for pilot

### ISSUE THREAD

**Issue by vicnbt** [spaceshipyard/mars-rover-dispatcher#20]

**Comment by vicnbt** [comment]
![image](https://user-images.githubusercontent.com/2864268/38055877-942dca96-32e3-11e8-9e3c-0ce0ff56a3ea.png)
make some changes in 20 branch, what do you think?

**Comment by chaos-adept** [comment]
it looks great, it is much better than we have currently.

There are minor remarks:
![image](https://user-images.githubusercontent.com/574757/38072032-4b7daec0-332d-11e8-8658-88effa6a6709.png)

**Comment by vicnbt** [comment]
![image](https://user-images.githubusercontent.com/2864268/38213581-743bcf04-36ca-11e8-9248-54933e0a861b.png)

**Comment by vicnbt** [comment]
need to add keyboard shortcuts and write key names on controls

**Comment by vicnbt** [comment]
![image](https://user-images.githubusercontent.com/2864268/38277133-02f01e6e-37a0-11e8-83d3-02410ac89784.png)

**Comment by vicnbt** [comment]
could we close this ticket? 
@chaos-adept could you update micro-conf.xyz:8082, please?
I plan to run a copy on my virtual cloud soon.

**Comment by chaos-adept** [comment]
It has been done already.
it makes sense to just close this ticket
