### ISSUE TITLE
Fix bug with camera control (losing control)

### ISSUE THREAD

**Issue by vicnbt** [spaceshipyard/mars-rover-dispatcher#25]
currently robot could stuck with camera control command and pilot lose control
steps:
1. Send moving command
2. Send Camera command
3. Send stop command
ER:
robot stops
AR:
robot continue moving and doesn't react on any commands

**Comment by vicnbt** [comment]
@chaos-adept if have time will try to fix it today, please check this too, will try to run robot tomorrow on the mars

**Comment by vicnbt** [comment]
probably fixed here
https://github.com/spaceshipyard/mars-rover-dispatcher/commit/75949a1aad1f6b666cee3dc16c58bdb719e58c49
need to check on the real robot

**Comment by vicnbt** [comment]
the issue is still actual, probably related with poor internet connection

**Comment by vicnbt** [comment]
we need to force socket.io to use the WebSocket, current problem caused by using of longPolling

**Comment by chaos-adept** [comment]
for information, we have a sandbox for experiments which has certificates - https://github.com/Code-Rush-Experement/electronic-queue

**Comment by chaos-adept** [comment]
for information, i have tried the electronic-queue, and it works:
![image](https://user-images.githubusercontent.com/574757/41210968-3d604cea-6d3d-11e8-935e-63c4f3f5ead6.png)

**Comment by chaos-adept** [comment]
I have tried to run the dispatcher on the my laptop, and it works over websocket:
![image](https://user-images.githubusercontent.com/574757/41211309-2406c4ac-6d3f-11e8-8467-018bc39c6e9a.png)
`engine.io-client:socket socket receive: type "open", data "{"sid":"draL28yzhRwSg-tnAAAB","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}" +1ms`

**Comment by vicnbt** [comment]
on laptop with mock server runs with the web socket also

**Comment by chaos-adept** [comment]
i have implemented status of messages in the https://github.com/spaceshipyard/mars-rover-dispatcher/issues/26

**Comment by chaos-adept** [comment]
the workaround for proxy blocking is under progress in #31

**Comment by vicnbt** [comment]
fixed, tested
