### ISSUE TITLE
try to use different ping settings for socket io

### ISSUE THREAD

**Issue by vicnbt** [spaceshipyard/mars-rover-dispatcher#29]

**Comment by vicnbt** [comment]
@chaos-adept, check the last commit, set polling to 500ms
it works, not very nice but could help a lot 500ms is better then 10seconds
![image](https://user-images.githubusercontent.com/2864268/41620751-56261584-7413-11e8-9fe1-22ee0e816182.png)

**Comment by chaos-adept** [comment]
i cant find any objections to merge it into master, it is totally fine,
i am not sure that we will need it, if #31 helps fix issue with websocket
