### ISSUE TITLE
Make proximity usage configurable

### ISSUE THREAD

**Issue by vnabatov** [spaceshipyard/mars-rover-dispatcher#38]

**Comment by vicnbt** [comment]
now it is hardcoded

**Comment by vicnbt** [comment]
we expect them to be installed soon, but for consistency it should be configurable

**Comment by chaos-adept** [comment]
@vnabatov 
They are configurable by using: 
`process.env.disableProximity`

for referece:
`arduino/control-modules/proximity.js`
`
...
function setup ({five}, registerCmd) {
  if (process.env.disableProximity === 'true') {
    console.warn('proximity sensors are disabled')
    return
  }
...
`

I suppose that we could just resolve this issue, if you have any objections let me know please
