### ISSUE TITLE
Remove vulnerable packages

### ISSUE THREAD

**Issue by vnabatov** [spaceshipyard/mars-rover-dispatcher#39]

**Comment by vnabatov** [comment]
![image](https://user-images.githubusercontent.com/2864268/44309001-0fe12480-a3c8-11e8-8657-2a56e5f4534c.png)

**Comment by vnabatov** [comment]
founde here:
https://github.com/spaceshipyard/mars-rover-node-bridge
https://github.com/spaceshipyard/mars-rover-dispatcher

**Comment by chaos-adept** [comment]
https://github.com/spaceshipyard/mars-rover-dispatcher has been fixed

**Comment by chaos-adept** [comment]
https://github.com/spaceshipyard/mars-rover-node-bridge has been fixed
