### ISSUE TITLE
Fix camera movement controls

### ISSUE THREAD

**Issue by vnabatov** [spaceshipyard/mars-rover-dispatcher#40]

**Comment by vnabatov** [comment]
added PR https://github.com/spaceshipyard/mars-rover-dispatcher/pull/43/files

**Comment by vnabatov** [comment]
![image](https://user-images.githubusercontent.com/2864268/53444203-95502c00-3a1e-11e9-8fe4-73db12ed5606.png)

**Comment by vnabatov** [comment]
ranges don't move with arrows clicks, need more refactoring if this approach works

**Comment by chaos-adept** [comment]
@vnabatov 
during review small cosmetic refactoring and fixes were added, 
the ranges are updated according to the incremental changes, also the bug with getting value from the range event was fixed, so It makes sense to merge this code in the master.

**Comment by chaos-adept** [comment]
the changes were merged into master and deployed on the "PROD"
